[target.aarch64-linux-android]
ar = "${env.ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/darwin-x86_64/bin/llvm-ar"
linker = "${env.ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/darwin-x86_64/bin/aarch64-linux-android21-clang"
rustflags = ["-C", "link-arg=-shared"]

[target.aarch64-unknown-linux-ohos]
ar = "${env.HARMONYOS_NDK_ROOT}/llvm/bin/llvm-ar"
linker = "${env.HARMONYOS_NDK_ROOT}/llvm/bin/aarch64-unknown-linux-ohos-clang"
rustflags = ["-C", "link-arg=-shared"]

[target.aarch64-apple-ios]
linker = "xcrun -sdk iphoneos clang"
rustflags = [
  "-C", "link-arg=-static",
  "-C", "link-arg=-fembed-bitcode",
  "-C", "link-arg=-isysroot",
  "-C", "link-arg=$(xcrun --sdk iphoneos --show-sdk-path)"
]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-C", "link-arg=-static"]

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=--import-memory",
  "-C", "link-arg=--initial-memory=65536",
  "-C", "link-arg=--max-memory=65536",
  "-C", "link-arg=--export-table"
]

[target.x86_64-pc-windows-msvc]
linker = "lld-link"

[env]
CC_x86_64_pc_windows_msvc = "clang-cl"
CXX_x86_64_pc_windows_msvc = "clang-cl"
AR_x86_64_pc_windows_msvc = "llvm-lib"
